# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="created",
            field=models.DateField(default="2023-12-01"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="due_date",
            field=models.DateField(default="2023-12-01"),
        ),
    ]
