# Generated by Django 4.2.7 on 2023-12-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_todolist_completed_alter_todolist_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={},
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="created",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="due_date",
        ),
    ]
